name: 'Manifest Cyber SBOM Transmitter'
description: 'Transmit an SBOM to your Manifest Cyber account'
inputs:
  apiKey: 
    description: 'An API key generated in the Manifest app'
    required: true
  bomFilePath: 
    description: 'The location of a generated SBOM file. Accepts CycloneDX or SPDX SBOMs in JSON.'
    required: true
  sbom-publish:
    description: 'Whether or not to publish the SBOM to the Manifest Cyber platform'
    required: true
  relationship: 
    description: 'The relationship of the software to your organization (e.g. first- vs third-party). In most cases, this will be `first`.'
    required: false
    default: 'first'
  source: 
    description: 'The source of the uploaded SBOM.'
    required: false
    default: 'github-action'
  sbom-name: 
    description: 'The SBOM name, defaults to repository name'
    required: false
  sbom-version: 
    description: 'The SBOM version, defaults to environment variable tag, or commit hash'
    required: false
  sbom-output: 
    description: 'The SBOM output format, Supports: spdx-json | cyclonedx-json'
    required: false
    default: 'cyclonedx-json'
  sbom-generator:
    description: 'The SBOM generator, defaults to syft'
    required: false
    default: 'syft'
  sbom-generator-flags:
    description: 'ADVANCED USERS: Flags the Manifest CLI passes through to the generator'
    required: false

runs:
  using: 'node16'
  main: 'index.js'
