name: 'Manifest Cyber SBOM Transmitter'
description: 'Transmit an SBOM to your Manifest Cyber account'
inputs:
  apiKey: 
    description: 'An API key generated in the Manifest app'
    required: true
  bomFilePath: 
    description: 'The location of an sbom file'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
