name: 'Manifest Cyber SBOM Transmitter'
description: 'Transmit an SBOM to your Manifest Cyber account'
inputs:
  apiKey: 
    description: 'An API key generated in the Manifest app'
    required: true
  bomFilePath: 
    description: 'The location of an sbom file'
    required: true
  sbom-name: 
    description: 'SBOM name, defaults to repository name'
    required: false
  sbom-version: 
    description: 'SBOM version, defaults to environment variable tag, or commit hash'
    required: false
  sbom-output: 
    description: 'SBOM output format, supports: spdx-json | cyclonedx-json'
    default: cyclonedx-json
    required: false
runs:
  using: 'node16'
  main: 'index.js'
